export { default as Student } from './student/Student';
export { default as Course } from './course/Course';
export { default as Login } from './form page/Login';
export { default as Signup } from './form page/signup';
export { default as User } from './user/User';
export { default as Role } from './user/role';
export { default as AddRole } from './form page/AddRole';
export { default as EditStudentPage } from './student/editForm';
export { default as AdmissionForm } from './register_student/addRegStudent';
export { default as RegStudent } from './register_student/regStudent';
export { default as UpdateReg } from './register_student/updateReg';
export { default as EditForm } from './student/editForm';
export { default as UpdateCourse } from './course/UpdateCourse';
export { default as UpdateUser } from './user/UpdateUser';
export { default as UpdateRole } from './user/UpdateRole';
